name: Cache

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: JobContext
      run: echo "$JOB_CONTEXT"
    - name: Restore npm cache
      uses: ./
      id: cache
      with:
        path: |
          "$JOB_CONTEXT"/**
          "$JOB_CONTEXT"
        key: lastTest-${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('salt.txt') }}
    - run: npm install
      if: steps.cache.outputs.cache-hit != 'true'
    - run: npm run build
      if: steps.cache.outputs.cache-hit != 'true'
